name: DNS解析检查 - Cloudflare IP

on:
  # 手动触发
  workflow_dispatch:
  # 定时触发（每12小时）
#  schedule:
#    - cron: '0 */12 * * *'
  # 当domain.txt文件发生变化时触发
  push:
    paths:
      - 'domain.txt'

jobs:
  dns-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install dnspython requests

    - name: 读取域名并查询DNS解析
      id: dns_query
      run: |
        # 运行DNS查询脚本
        python dns_query.py

    - name: 配置Git用户
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: 提交结果到仓库
      run: |
        # 检查文件是否有变化
        if git diff --quiet api.txt; then
          echo "结果文件没有变化，无需提交"
        else
          git add api.txt
          git commit -m "自动更新Cloudflare IP列表 $(date)"
          git push
        fi

    - name: 显示结果摘要
      run: |
        if [ -f "api.txt" ]; then
          echo "=== 查询结果摘要 ==="
          echo "文件内容预览:"
          head -20 api.txt
          echo "..."
          echo "文件大小: $(wc -l < api.txt) 行"
        else
          echo "未生成结果文件"
        fi
